import type { CampusCode, ServiceSearchResult } from '@/types/campus';
import type { BuildingCatalogRecord } from './types';

const MAPS = 'https://www.concordia.ca/maps/buildings';

function page(code: string): string {
  return `${MAPS}/${code.toLowerCase()}.html`;
}

function row(
  campusId: CampusCode,
  code: string,
  name: string,
  address: string,
  extra: Partial<BuildingCatalogRecord> = {}
): BuildingCatalogRecord {
  return {
    campusId,
    code,
    name,
    address,
    sourceUrl: page(code),
    aliases: extra.aliases ?? [name, code],
    ...extra,
  };
}

/**
 * Consolidated building database.
 * Generated by `npm run sync:buildings` from website directory + maps XML,
 * merged with hand-curated detail pages in catalog.overrides.ts.
 * Coordinates still come from Open Data `facilities/buildinglist/`.
 */
export const BUILDING_CATALOG: BuildingCatalogRecord[] = [
  row('sgw', 'B', 'B Annex', '2160 Bishop St.', {
    aliases: [
      'B Annex',
      'B',
    ],
    services: ['Engineering and Computer Science Association'],
  }),
  row('sgw', 'CL', 'CL Annex', '1665 Ste-Catherine St. W.', {
    aliases: [
      'CL Annex',
      'CL',
    ],
    services: ['Concordia Continuing Education'],
    amenities: [
      'Accessible',
      'ATM',
      'Info desk',
    ],
  }),
  row('sgw', 'D', 'D Annex', '2140 Bishop St.', {
    aliases: [
      'D Annex',
      'D',
    ],
    services: ['Theological Studies'],
  }),
  row('sgw', 'EN', 'EN Annex', '2070 Mackay St.', {
    aliases: [
      'EN Annex',
      'EN',
    ],
  }),
  row('sgw', 'ER', 'ER Building', '2155 Guy St.', {
    aliases: [
      'ER Building',
      'ER',
    ],
    departments: [
      'Computer Science and Software Engineering',
      'Department of Creative Arts Therapies',
      'engAge: Centre for Research on Aging',
      'Next-Generation Cities Institute',
      'Simone de Beauvoir Institute',
      'Sustainability in the Digital Age',
      'Urban Studies',
    ],
    amenities: [
      'Accessible',
      'ATM',
    ],
  }),
  row('sgw', 'EV', 'Engineering, Computer Science and Visual Arts Integrated Complex', '1515 Ste-Catherine St. W.', {
    aliases: [
      'EV',
      'Engineering, Computer Science and Visual Arts Integrated Complex',
      'EV Building',
      'Engineering and Visual Arts',
    ],
    overview: 'Opened in 2005, the 17-storey EV complex unites the Gina Cody School of Engineering and Computer Science and the Faculty of Fine Arts. Two towers connected on every floor, with labs, studios, a fitness centre, and an underground tunnel to GM and Guy-Concordia metro.',
    accessibility: [
      'Accessible entrance with an automated door',
      'Accessible elevator',
    ],
    services: [
      'FOFA Gallery',
      'LeGym',
    ],
    departments: [
      'Art Education',
      'Art History',
      'Building, Civil and Environmental Engineering',
      'Contemporary Dance',
      'Centre for Composites (CONCOM)',
      'Cybersecurity and Intelligent Systems Engineering (CISE)',
      'Centre for Pattern Recognition and Machine Intelligence (CENPARMI)',
      'Design and Computation Arts',
      'Electrical and Computer Engineering',
      'Faculty of Fine Arts',
      'Gina Cody School of Engineering and Computer Science',
      'Mechanical, Industrial and Aerospace Engineering',
      'Recreation and Athletics',
      'Studio Arts',
      'Zero Energy Building Studies, Centre for',
    ],
    amenities: [
      'Accessible',
      'ATM',
      'Info desk',
    ],
  }),
  row('sgw', 'FA', 'FA Annex', '2060 Mackay St.', {
    aliases: [
      'FA Annex',
      'FA',
    ],
    departments: ['Religions and Cultures, Department of'],
  }),
  row('sgw', 'FB', 'Faubourg Building', '1250 Guy St. / 1600 Ste-Catherine St. W.', {
    aliases: [
      'Faubourg Building',
      'FB',
    ],
    services: [
      'Enrolment Services / Office of the Registrar / Student Recruitment',
      'Environmental Health and Safety',
      'Examinations Office',
      'Human Resources',
      'Office of Sustainability',
      'Records Management and Archives (RMA) Office',
      'Senior non-credit program',
    ],
    departments: [
      'Classics, Modern Languages & Linguistics',
      'Concordia Continuing Education',
      'District 3 Innovation Center',
      'Mel Hoppenheim School of Cinema',
      'Montreal Institute for Genocide and Human Rights Studies (MIGS)',
    ],
    amenities: [
      'Accessible',
      'Parking',
    ],
  }),
  row('sgw', 'FG', 'Faubourg Ste-Catherine Building', '1610 Ste-Catherine St. W.', {
    aliases: [
      'Faubourg Ste-Catherine Building',
      'FG',
    ],
    services: [
      'Classrooms',
      'RMA Research Room and Vault',
    ],
    departments: ['Education'],
    amenities: [
      'Accessible',
      'ATM',
      'Info desk',
    ],
  }),
  row('sgw', 'GA', 'Grey Nuns Annex', '1211-1215 St-Mathieu St.', {
    aliases: [
      'Grey Nuns Annex',
      'GA',
    ],
    departments: ['Department of Education'],
  }),
  row('sgw', 'GM', 'Guy-De Maisonneuve Building', '1550 De Maisonneuve Blvd. W.', {
    aliases: [
      'GM',
      'Guy-De Maisonneuve',
      'Guy De Maisonneuve',
      'Guy-Concordia',
      'Guy-De Maisonneuve Building',
    ],
    overview: 'Completed in 1966 above Guy-Concordia metro, GM now houses administrative offices and School of Performance studios. Connected to EV and the metro by underground tunnels.',
    accessibility: [
      'Accessible entrance with an automated door',
      'Accessible elevator',
    ],
    services: [
      'Access Centre for Students with Disabilities',
      'Environmental Health and Safety',
      'Facilities Management',
      'Financial Aid & Awards Office',
      'Financial Services',
      'Graduate Studies',
      'Health Services',
      'Institute for Co-operative Education',
      'International Students Office',
      'Office of the Chief Communications Officer',
      'Office of the President',
      'Office of the Provost & VP, Academic',
      'Office of Rights and Responsibilities',
      'Office of Sustainability',
      'Office of the VP, Research & Graduate Studies',
      'Office of the VP, Services and Sustainability',
      'Ombuds Office',
      'University Advancement',
      'University Communications Services',
    ],
    departments: [
      'Contemporary Dance',
      'Music',
      'Theatre',
    ],
    amenities: [
      'Accessible',
      'Bike parking',
      'Info desk',
    ],
  }),
  row('sgw', 'GN', 'Grey Nuns Building', '1190 Guy St. / 1175 St-Mathieu St.', {
    aliases: [
      'GN',
      'Grey Nuns',
      'Grey Nuns Building',
      'Grey Nuns Mother House',
    ],
    overview: 'Former Grey Nuns Mother House (1871), acquired in 2007. Residence for about 600 undergraduates, with a reading room, observation nursery, and kitchen serving both campuses.',
    accessibility: [
      'Accessibility ramp',
      'Accessible entrance with an automated door',
      'Accessible elevator',
    ],
    venues: [
      'Classroom entrance (1175 St-Mathieu St.)',
      'Grey Nuns Garden',
    ],
    library: 'greynuns',
    services: [
      'Class Entrance: 1175 St-Mathieu St.',
      'CUSP: 1175 St-Mathieu St. (temporary)',
      'Daycare Centre: 1185 St-Mathieu St.',
      'Grey Nuns Library (reading Room and Group Study Rooms)',
      'Residences',
      'Summer Accomodation',
    ],
    departments: ['Dept. of Philosophy: 1175 St-Mathieu St. (temporary)'],
  }),
  row('sgw', 'H', 'Henry F. Hall Building', '1455 De Maisonneuve Blvd. W.', {
    aliases: [
      'H',
      'Hall',
      'Henry F. Hall',
      'Hall Building',
      'Henry F. Hall Building',
    ],
    overview: 'Completed in 1966, the Hall Building is a Brutalist academic and social hub. Social-science departments, classrooms, engineering labs, the Student Success Centre, Concordia Theatre, Hive Café, Reggie’s, and the People’s Potato.',
    accessibility: [
      'Accessible entrance with an automated door',
      'Accessible elevator',
    ],
    venues: [
      'Concordia Theatre',
      'Reggie\'s',
      'Sir George Williams University Alumni Auditorium',
    ],
    services: [
      'Campus Safety and Prevention Services',
      'Concordia Student Union',
      'Espace Franco',
      'First Stop',
      'IT Service Desk',
      'NouLa Black Student Centre',
      'Office of Student Life and Engagement',
      'Otsenhákta Student Centre',
      'Welcome Crew Office',
      'Zen Den',
    ],
    departments: [
      'Economics',
      'Geography, Planning & Environment',
      'Political Science',
      'School of Irish Studies',
      'Sociology and Anthropology',
    ],
    amenities: [
      'Accessible',
      'ATM',
      'Bike parking',
      'Info desk',
    ],
  }),
  row('sgw', 'K', 'K Annex', '2150 Bishop St.', {
    aliases: [
      'K Annex',
      'K',
    ],
    services: [
      'Concordia Coop Bookstore',
      'CUPFA',
    ],
  }),
  row('sgw', 'LB', 'J.W. McConnell Building', '1400 De Maisonneuve Blvd. W.', {
    aliases: [
      'LB',
      'McConnell',
      'J.W. McConnell',
      'J.W. McConnell Building',
      'Webster',
      'Webster Library',
    ],
    overview: 'Opened in 1992. Lower floors hold student services, bookstore, print shop and gallery; floors 2–5 are the R. Howard Webster Library. Linked by tunnel to Hall and Guy-Concordia metro.',
    accessibility: [
      'Accessible entrance with an automated door',
      'Accessible elevator',
    ],
    venues: [
      '4TH SPACE',
      'Atrium',
      'J.A. De Sève Cinema',
      'Leonard and Bina Ellen Art Gallery',
      'SHIFT Centre for Social Transformation',
    ],
    library: 'webster',
    services: [
      '4TH SPACE',
      'Birks Student Service Centre',
      'Concordia Book Stop',
      'Concordia Print Services',
      'J.A. De Sève Cinema',
      'Instructional & Information Technology Services (IITS)',
      'Leonard and Bina Ellen Art Gallery',
      'Office of the Registrar',
      'R. Howard Webster Library',
      'Sexual Assault Resource Centre (SARC)',
      'SHIFT Centre for Social Transformation',
      'Welcome Centre',
    ],
    departments: [
      'Centre for Interdisciplinary Studies in Society and Culture (CISSC)',
      'Centre for the Study of Learning and Performance',
      'Education',
      'English',
      'Études françaises',
      'History',
      'Mathematics & Statistics',
    ],
    amenities: [
      'Accessible',
      'ATM',
      'Bike parking',
      'Info desk',
      'Parking',
    ],
  }),
  row('sgw', 'LD', 'LD Building', '1424 Bishop St.', {
    aliases: [
      'LD Building',
      'LD',
    ],
    services: ['CSU Daycare & Nursery'],
  }),
  row('sgw', 'LS', 'Learning Square', '1535 De Maisonneuve Blvd. W.', {
    aliases: [
      'LS',
      'Learning Square',
      'Learning Square (LS Building)',
    ],
    services: [
      'IT Services — 1st floor',
      'IT Services — 2nd floor',
    ],
  }),
  row('sgw', 'MB', 'John Molson Building', '1450 Guy St.', {
    aliases: [
      'MB',
      'John Molson',
      'John Molson Building',
      'JMSB',
      'Molson',
    ],
    overview: 'Opened in 2009 at Guy and De Maisonneuve. 15 storeys with teaching amphitheatres, case rooms, research labs, and a tunnel under Guy Street to the metro and EV. LEED Silver.',
    accessibility: [
      'Accessible entrance with an automated door',
      'Accessible elevator',
    ],
    venues: [
      'Concordia Conference Centre, 9th Floor',
      'Cloud Deck',
      'Goodman Institute',
    ],
    services: [
      'Career management services',
      'John Molson Executive Centre',
      'Performing Arts Facilities',
    ],
    departments: [
      'Accountancy',
      'Contemporary Dance',
      'Executive MBA Program',
      'Finance',
      'Goodman Institute of Investment Management',
      'Management',
      'Marketing',
      'Music',
      'Supply Chain & Business Technology Management',
      'Theatre',
    ],
    amenities: ['Accessible'],
  }),
  row('sgw', 'MI', 'MI Annex', '2130 Bishop St.', {
    aliases: [
      'MI Annex',
      'MI',
    ],
  }),
  row('sgw', 'MU', 'MU Annex', '2170 Bishop St.', {
    aliases: [
      'MU Annex',
      'MU',
    ],
  }),
  row('sgw', 'P', 'P Annex', '2020 Mackay St.', {
    aliases: [
      'P Annex',
      'P',
    ],
  }),
  row('sgw', 'PR', 'PR Annex', '2100 Mackay St.', {
    aliases: [
      'PR Annex',
      'PR',
    ],
  }),
  row('sgw', 'Q', 'Q Annex', '2010 Mackay St.', {
    aliases: [
      'Q Annex',
      'Q',
    ],
  }),
  row('sgw', 'R', 'R Annex', '2050 Mackay St.', {
    aliases: [
      'R Annex',
      'R',
    ],
    departments: ['Religions and Cultures'],
  }),
  row('sgw', 'RR', 'RR Annex', '2040 Mackay St.', {
    aliases: [
      'RR Annex',
      'RR',
    ],
    departments: ['Liberal Arts College'],
  }),
  row('sgw', 'T', 'T Annex', '2030 Mackay St.', {
    aliases: [
      'T Annex',
      'T',
    ],
    services: ['Graduate Students Association'],
  }),
  row('sgw', 'V', 'V Annex', '2110 Mackay St.', {
    aliases: [
      'V Annex',
      'V',
    ],
    services: [
      'Centre 2110',
      'CUTV',
    ],
  }),
  row('sgw', 'VA', 'Visual Arts Building', '1395 René-Lévesque Blvd. W.', {
    aliases: [
      'VA',
      'Visual Arts',
      'Visual Arts Building',
    ],
    services: ['VAV Art Gallery'],
    departments: [
      'Art Education',
      'Art History',
      'Creative Arts Therapies',
      'Studio Arts',
    ],
    amenities: [
      'Accessible',
      'Bike parking',
      'Info desk',
    ],
  }),
  row('sgw', 'X', 'X Annex', '2080 Mackay St.', {
    aliases: [
      'X Annex',
      'X',
    ],
    services: ['Concordia International'],
  }),

  row('loy', 'AD', 'Administration Building', '7141 Sherbrooke St. W.', {
    aliases: [
      'Administration Building',
      'AD',
    ],
    services: [
      'Access Centre for Students with Disabilities',
      'Centre for Teaching and Learning',
      'Counselling and Psychological Services',
      'Dean of Students',
      'Health Services',
      'Loyola International College',
      'Loyola Landing',
      'Provost and VP, Academic',
      'Welcome Crew Office',
    ],
    departments: ['Faculty of Arts and Science'],
    amenities: [
      'Accessible',
      'Bike parking',
      'Info desk',
      'Parking',
    ],
  }),
  row('loy', 'BB', 'BB Annex', '3502 Belmore Ave.', {
    aliases: [
      'BB Annex',
      'BB',
    ],
    services: ['CPE les P\'tits Profs Daycare'],
  }),
  row('loy', 'BH', 'BH Annex', '3500 Belmore Ave.', {
    aliases: [
      'BH Annex',
      'BH',
    ],
    services: ['CPE les P\'tits Profs Daycare'],
  }),
  row('loy', 'CC', 'Central Building', '7141 Sherbrooke St. W.', {
    aliases: [
      'CC',
      'Central',
      'Central Building',
    ],
    services: [
      'Concordia Student Union',
      'Loyola College for Diversity and Sustainability and Loyola',
    ],
    amenities: [
      'Accessible',
      'Bixi',
      'Info desk',
    ],
  }),
  row('loy', 'CJ', 'Communication Studies and Journalism Building', '7141 Sherbrooke St. W.', {
    aliases: [
      'Communication Studies and Journalism Building',
      'CJ',
    ],
    services: ['Campus Retail Stores'],
    departments: [
      'Communication Studies',
      'Journalism',
    ],
    amenities: ['Accessible'],
  }),
  row('loy', 'DO', 'Stinger Dome', '7141 Sherbrooke St. W.', {
    aliases: [
      'DO',
      'Stinger Dome',
      'Stinger Dome (seasonal)',
    ],
    departments: ['Stingers.ca'],
  }),
  row('loy', 'FC', 'F.C. Smith Building', '7141 Sherbrooke St. W.', {
    aliases: [
      'FC',
      'F.C. Smith Building',
      'F. C. Smith Building',
    ],
    services: [
      'Cazalet Theatre',
      'Concordia Multi-faith and Spirituality Centre',
      'F.C. Smith Auditorium',
    ],
  }),
  row('loy', 'GE', 'Centre for Structural and Functional Genomics', '7141 Sherbrooke St. W.', {
    aliases: [
      'Centre for Structural and Functional Genomics',
      'GE',
    ],
    services: ['Centre for Structural and Functional Genomics'],
    amenities: ['Accessible'],
  }),
  row('loy', 'HA', 'Hingston Hall, wing HA', '7141 Sherbrooke St. W.', {
    aliases: [
      'Hingston Hall, wing HA',
      'HA',
    ],
    services: ['Student Residence'],
    amenities: [
      'Accessible',
      'Parking',
    ],
  }),
  row('loy', 'HB', 'Hingston Hall, wing HB', '7141 Sherbrooke St. W.', {
    aliases: [
      'Hingston Hall, wing HB',
      'HB',
    ],
    services: [
      'CUFA',
      'Student Residence',
    ],
    amenities: [
      'Accessible',
      'Parking',
    ],
  }),
  row('loy', 'HC', 'Hingston Hall, wing HC', '7141 Sherbrooke St. W.', {
    aliases: [
      'Hingston Hall, wing HC',
      'HC',
    ],
    services: ['Student Residence'],
    amenities: ['Parking'],
  }),
  row('loy', 'HU', 'Applied Science Hub', '7141 Sherbrooke St. W.', {
    aliases: [
      'Applied Science Hub',
      'HU',
    ],
    amenities: ['Accessible'],
  }),
  row('loy', 'JR', 'Jesuit Residence', '7141 Sherbrooke St. W.', {
    aliases: [
      'Jesuit Residence',
      'JR',
    ],
    services: ['Student Residence'],
    amenities: ['Parking'],
  }),
  row('loy', 'PC', 'PERFORM Centre', '7200 Sherbrooke St. W.', {
    aliases: [
      'PERFORM Centre',
      'PC',
    ],
    services: ['School of Health'],
    amenities: [
      'Accessible',
      'Info desk',
      'Parking',
    ],
  }),
  row('loy', 'PS', 'Physical Services Building', '7141 Sherbrooke St. W.', {
    aliases: [
      'Physical Services Building',
      'PS',
    ],
    services: [
      'Environmental Health and Safety',
      'Facilities Management',
    ],
    amenities: ['Accessible'],
  }),
  row('loy', 'PT', 'Oscar Peterson Concert Hall', '7141 Sherbrooke St. W.', {
    aliases: [
      'Oscar Peterson Concert Hall',
      'PT',
    ],
    services: ['Concert Hall'],
    departments: ['Oscar Peterson Concert Hall'],
    amenities: ['Accessible'],
  }),
  row('loy', 'PY', 'Psychology Building', '7141 Sherbrooke St. W.', {
    aliases: [
      'Psychology Building',
      'PY',
    ],
    departments: [
      'Centre for clinical research in health (CCRH)',
      'Psychology',
    ],
    amenities: ['Info desk'],
  }),
  row('loy', 'QA', 'Quadrangle', '7141 Sherbrooke St. W.', {
    aliases: [
      'Quadrangle',
      'QA',
    ],
    amenities: ['Accessible'],
  }),
  row('loy', 'RA', 'Recreation and Athletics Complex', '7200 Sherbrooke St. W.', {
    aliases: [
      'Recreation and Athletics Complex',
      'RA',
    ],
    services: [
      'Ed Meagher Arena',
      'Gymnasium',
    ],
    amenities: [
      'Accessible',
      'Parking',
    ],
  }),
  row('loy', 'RF', 'Loyola Jesuit Hall and Conference Centre', '7141 Sherbrooke St. W.', {
    aliases: [
      'Loyola Jesuit Hall and Conference Centre',
      'RF',
    ],
    services: [
      'Conference services',
      'Loyola Jesuit Hall and Conference Centre',
    ],
    amenities: ['Accessible'],
  }),
  row('loy', 'SC', 'Student Centre', '7141 Sherbrooke St. W.', {
    aliases: [
      'Student Centre',
      'SC',
    ],
    services: ['Food Services'],
    amenities: ['Accessible'],
  }),
  row('loy', 'SH', 'Future Buildings Laboratory', '7141 Sherbrooke St. W.', {
    aliases: [
      'SH',
      'Future Buildings Laboratory',
      'Solar House',
    ],
  }),
  row('loy', 'SP', 'Richard J. Renaud Science Complex', '7141 Sherbrooke St. W.', {
    aliases: [
      'SP',
      'Science Complex',
      'Richard J. Renaud Science Complex',
      'Renaud',
    ],
    services: [
      'Campus Safety and Prevention Services',
      'Science College',
      'Science Technical Centre',
    ],
    departments: [
      'Biology',
      'Centre for Biological Applications of Mass Spectrometry',
      'Centre for NanoScience Research',
      'Centre for Research in Molecular Modeling',
      'Centre for Studies in Behavioral Neurobiology',
      'Chemistry & Biochemistry',
      'Health, Kinesiology & Applied Physiology',
      'Physics',
      'Psychology',
    ],
    amenities: [
      'Accessible',
      'Info desk',
    ],
  }),
  row('loy', 'TA', 'Terrebonne Building', '7079 de Terrebonne St.', {
    aliases: [
      'Terrebonne Building',
      'TA',
    ],
    departments: ['Centre for the Arts in Human Development'],
    amenities: ['Parking'],
  }),
  row('loy', 'VE', 'Vanier Extension', '7141 Sherbrooke St. W.', {
    aliases: [
      'VE',
      'Vanier Extension',
    ],
    library: 'vanier',
    services: ['Library'],
    departments: ['Applied Human Sciences'],
    amenities: [
      'Accessible',
      'Bike parking',
    ],
  }),
  row('loy', 'VL', 'Vanier Library Building', '7141 Sherbrooke St. W.', {
    aliases: [
      'VL',
      'Vanier',
      'Vanier Library',
      'Georges P. Vanier Library',
      'Vanier Library Building',
    ],
    overview: 'Named for Loyola alumnus Georges P. Vanier. Library since 1964; doubled in 1989 with the Vanier Extension. Silent and collaborative study, 22 learning spaces, and bookable group rooms.',
    accessibility: [
      'Accessible entrance with an automated door',
      'Accessible elevator',
    ],
    library: 'vanier',
    services: ['Library'],
    amenities: [
      'Accessible',
      'Info desk',
    ],
  }),
];

const catalogByKey = new Map(
  BUILDING_CATALOG.map((record) => [`${record.campusId}-${record.code.toUpperCase()}`, record])
);

export function getBuildingCatalogRecord(
  campusId: CampusCode,
  code: string
): BuildingCatalogRecord | undefined {
  return catalogByKey.get(`${campusId}-${code.trim().toUpperCase()}`);
}

/** Flattened services/departments index for campus search. */
export function getCampusServices(campusId: CampusCode): ServiceSearchResult[] {
  const results: ServiceSearchResult[] = [];

  BUILDING_CATALOG.filter((building) => building.campusId === campusId).forEach((building) => {
    (building.services ?? []).forEach((label, index) => {
      results.push({
        id: `svc-${campusId}-${building.code}-${index}-${label}`,
        label,
        buildingName: building.name,
        buildingCode: building.code,
        kind: 'service',
      });
    });
    (building.departments ?? []).forEach((label, index) => {
      results.push({
        id: `dept-${campusId}-${building.code}-${index}-${label}`,
        label,
        buildingName: building.name,
        buildingCode: building.code,
        kind: 'department',
      });
    });
  });

  return results.sort((a, b) =>
    `${a.label} - ${a.buildingName}`.localeCompare(`${b.label} - ${b.buildingName}`)
  );
}
