import type { CampusCode, ServiceSearchResult } from '@/types/campus';
import type { BuildingCatalogRecord } from './types';

const MAPS = 'https://www.concordia.ca/maps/buildings';

function page(code: string): string {
  return `${MAPS}/${code.toLowerCase()}.html`;
}

function row(
  campusId: CampusCode,
  code: string,
  name: string,
  address: string,
  extra: Partial<BuildingCatalogRecord> = {}
): BuildingCatalogRecord {
  return {
    campusId,
    code,
    name,
    address,
    sourceUrl: page(code),
    aliases: extra.aliases ?? [name, code],
    ...extra,
  };
}

/**
 * Consolidated building database.
 * Generated by `npm run sync:buildings` from the website directory,
 * crawled building detail pages, maps XML, and catalog.overrides.ts.
 * Coordinates still come from Open Data `facilities/buildinglist/`.
 */
export const BUILDING_CATALOG: BuildingCatalogRecord[] = [
  row('sgw', 'B', 'B Annex', '2160 Bishop St.', {
    aliases: [
      'B Annex',
      'B',
    ],
    overview: 'Built between 1890 and 1891, this annex features a limestone façade and understated ornamentation around the windows. It was once a private home and even served as a student housing co-op in the 1960s. Concordia acquired the annex in 1969, and it now provides offices and shared spaces for student and community services.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    services: ['Engineering and Computer Science Association'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/b/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750701724050.jpg',
  }),
  row('sgw', 'CL', 'CL Annex', '1665 Ste-Catherine St. W.', {
    aliases: [
      'CL Annex',
      'CL',
    ],
    overview: 'Located on the Sir George Williams Campus, the CL Annex is a dedicated space for learning and academic services. The building is home to classrooms and facilities that support Concordia Continuing Education programs, providing a convenient downtown location for students pursuing professional development and lifelong learning.',
    accessibility: [
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
      'Accessible building elevator This building entrance is equipped with an accessible elevator.',
    ],
    services: ['Concordia Continuing Education'],
    amenities: [
      'Accessible',
      'ATM',
      'Info desk',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/cl/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750702106400.jpg',
  }),
  row('sgw', 'D', 'D Annex', '2140 Bishop St.', {
    aliases: [
      'D Annex',
      'D',
    ],
    overview: 'This row house was built in 1891 as a twin to the neighbouring MI Annex, also featuring red Scottish sandstone and Romanesque-inspired detailing. After years as a private residence, it was acquired by Concordia in 1971. Its distinct gabled roofline and original bay windows hint at its 19th-century residential roots.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    services: ['Theological Studies'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/d/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750702147171.jpg',
  }),
  row('sgw', 'EN', 'EN Annex', '2070 Mackay St.', {
    aliases: [
      'EN Annex',
      'EN',
    ],
    overview: 'This four-storey row house was built in 1940. It has an Art Deco flair, with rounded balconies and decorative concrete framing its windows and doors. Acquired in 1971 by the university, it now houses offices and student services.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    departments: ['Research Chair on Gambling'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/en/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750702290723.jpg',
  }),
  row('sgw', 'ER', 'ER Building', '2155 Guy St.', {
    aliases: [
      'ER Building',
      'ER',
    ],
    overview: 'Built in 1954, the ER Building is a 14-storey office tower on Concordia\'s Sir George Williams Campus. It houses academic departments and research centres and institutes. Concordia occupies space on 11 floors.',
    accessibility: [
      'Accessibility ramp This building entrance is equipped with an',
      'accessibility ramp.',
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
      'Accessible building elevator This building entrance is equipped with an accessible elevator.',
    ],
    services: ['Concordia University Part-time Faculty Association (CUPFA)'],
    departments: [
      'Applied AI Institute',
      'Centre for Engineering in Society',
      'Computer Science and Software Engineering',
      'Creative Arts Therapies',
      'engAGE: Centre for Research on Aging',
      'Next-Generation Cities Institute',
      'Simone de Beauvoir Institute',
      'Sustainability in the Digital Age',
      'Urban Studies',
      'Department of Creative Arts Therapies',
    ],
    amenities: [
      'Accessible',
      'ATM',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/er/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750702362372.jpg',
  }),
  row('sgw', 'EV', 'Engineering, Computer Science and Visual Arts Integrated Complex', '1515 Ste-Catherine St. W.', {
    aliases: [
      'EV',
      'Engineering, Computer Science and Visual Arts Integrated Complex',
      'EV Building',
      'Engineering and Visual Arts',
    ],
    overview: 'Opened in 2005, the 17-storey EV complex unites the Gina Cody School of Engineering and Computer Science and the Faculty of Fine Arts. Two towers connected on every floor, with labs, studios, a fitness centre, and an underground tunnel to GM and Guy-Concordia metro.',
    accessibility: [
      'Accessible entrance with an automated door',
      'Accessible elevator',
    ],
    venues: [
      'Abe and Harriet Gold Atrium',
      'FOFA Gallery',
      'Norman D. Hébert, LLD Meeting Room',
      'York Amphitheatre',
    ],
    services: [
      'Le Gym',
      'Zen Den',
      'FOFA Gallery',
      'LeGym',
    ],
    departments: [
      'Art Education',
      'Art History',
      'Building, Civil and Environmental Engineering',
      'Centre for Composites (CONCOM)',
      'Centre for Pattern Recognition and Machine Intelligence (CENPARMI)',
      'Centre for Zero Energy Building Studies',
      'Chemical and Materials Engineering',
      'Cybersecurity and Intelligent Systems Engineering',
      'Design and Computation Arts',
      'Electrical and Computer Engineering',
      'Faculty of Fine Arts',
      'Gina Cody School of Engineering and Computer Science',
      'Mechanical, Industrial and Aerospace Engineering',
      'Recreation and Athletics',
      'School of Performance (Contemporary Dance)',
      'Studio Arts',
      'Contemporary Dance',
      'Zero Energy Building Studies, Centre for',
    ],
    amenities: [
      'Accessible',
      'ATM',
      'Info desk',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/ev/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750702823530.jpg',
  }),
  row('sgw', 'FA', 'FA Annex', '2060 Mackay St.', {
    aliases: [
      'FA Annex',
      'FA',
    ],
    overview: 'The FA Annex, a three-storey Victorian house built in 1875, stands out with its steep slate roof, detailed dormer windows and prominent stone bay window at the front. Once home to notable Montrealers, it became part of the university in 1970. Today, it hosts offices and student services.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    departments: ['Religions and Cultures, Department of'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/fa/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750702940372.jpg',
  }),
  row('sgw', 'FB', 'Faubourg Building', '1250 Guy St. / 1600 Ste-Catherine St. W.', {
    aliases: [
      'Faubourg Building',
      'FB',
    ],
    overview: 'The Faubourg Building, a 12-storey postmodern tower, opened in 1990 at the corner of Guy Street and Ste. Catherine Street West. Originally designed as a hotel, it became an office building and was acquired by Concordia in 1997. Today, it\'s home to Concordia Continuing Education and the Mel Hoppenheim School of Cinema , along with labs, classrooms, offices, study spaces and student services. The building is part of a larger complex that once hosted a Buick car showroom, bowling alley and the legendary Toe Blake\'s Tavern. Its red brick, green aluminum and glass exterior stands out with a distinctive sawtooth pattern along Guy Street. The Faubourg Building connects to the Faubourg Ste-Catherine (FG) and Grey Nuns Annex (GA) Buildings and offers indoor parking .',
    accessibility: [
      'Wheelchair lift This building is equipped with a',
      'wheelchair lift.',
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
      'Accessible building elevator This building entrance is equipped with an accessible elevator.',
    ],
    venues: ['District 3 Innovation Hub'],
    services: [
      'Enrolment Services / Office of the Registrar / Student Recruitment',
      'Environmental Health and Safety',
      'Examinations Office',
      'Human Resources',
      'Office of Sustainability',
      'Records Management and Archives (RMA) Office',
      'Senior non-credit program',
      'Study Hub',
    ],
    departments: [
      'Classics, Modern Languages and Linguistics',
      'Concordia Continuing Education',
      'Mel Hoppenheim School of Cinema',
      'Theological Studies',
      'District 3 Innovation Center',
      'Montreal Institute for Genocide and Human Rights Studies (MIGS)',
    ],
    amenities: [
      'Accessible',
      'Parking',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/fb/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750703069703.jpg',
  }),
  row('sgw', 'FG', 'Faubourg Ste-Catherine Building', '1610 Ste-Catherine St. W.', {
    aliases: [
      'Faubourg Ste-Catherine Building',
      'FG',
    ],
    overview: 'Located on the site of a former auto showroom, the Faubourg Ste-Catherine Building has a colourful history. Built in 1926, the building was originally a McLaughlin-Buick dealership and then later hosted a bowling alley, a pool room and a tavern. In 1985, the building was redeveloped into an indoor urban market inspired by Boston\'s Faneuil Hall, with an attached tower originally intended as a hotel. Today, the building houses classrooms as well as the Department of Education\'s Student Resource Centre . You can also find a selection of restaurants in the building\'s sunlit atrium.',
    accessibility: [
      'Wheelchair lift This building is equipped with a',
      'wheelchair lift.',
      'Accessibility ramp This building entrance is equipped with an',
      'accessibility ramp.',
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
      'Accessible building elevator This building entrance is equipped with an accessible elevator.',
    ],
    services: [
      'Records Management and Archives (RMA) Research Room and Vault',
      'Classrooms',
      'RMA Research Room and Vault',
    ],
    departments: ['Education'],
    amenities: [
      'Accessible',
      'ATM',
      'Info desk',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/fg/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750703205424.jpg',
  }),
  row('sgw', 'GA', 'Grey Nuns Annex', '1211-1215 St-Mathieu St.', {
    aliases: [
      'Grey Nuns Annex',
      'GA',
    ],
    overview: 'Built in stages between 1869 and 1925, the Grey Nuns Annex originally housed workers for the Grey Nuns\' hospital complex. It once included dorms, a bakery and workshops for painters and carpenters. Acquired by Concordia in 2014, the stone building now serves as a research and administrative hub for Concordia\'s Department of Education and other university services. Highlights include its preschool education lab and a modern footbridge linking it to the Faubourg (FB) Building . With its historic dormers and stone walls, the annex is a rare example of 19th-century institutional architecture preserved on campus.',
    accessibility: [
      'Accessibility ramp This building entrance is equipped with an',
      'accessibility ramp.',
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
    ],
    departments: [
      'Education',
      'Department of Education',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/ga/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750703691368.jpg',
  }),
  row('sgw', 'GM', 'Guy-De Maisonneuve Building', '1550 De Maisonneuve Blvd. W.', {
    aliases: [
      'GM',
      'Guy-De Maisonneuve',
      'Guy De Maisonneuve',
      'Guy-Concordia',
      'Guy-De Maisonneuve Building',
    ],
    overview: 'Completed in 1966 above Guy-Concordia metro, GM now houses administrative offices and School of Performance studios. Connected to EV and the metro by underground tunnels.',
    accessibility: [
      'Accessible entrance with an automated door',
      'Accessible elevator',
    ],
    services: [
      'Access Centre for Students with Disabilities',
      'Facilities Management',
      'Financial Aid and Awards Office',
      'Financial Services',
      'Graduate Studies',
      'Health Services',
      'Institute for Co-operative Education',
      'International Students Office',
      'Office of the President and Vice-Chancellor',
      'Office of the Provost and Vice-President, Academic',
      'Office of the Vice-President, Research, Innovation and Impact',
      'Office of the Vice-President, Services and Sustainability',
      'Ombuds Office',
      'University Communications Services',
      'Zen Den',
      'Environmental Health and Safety',
      'Office of the Chief Communications Officer',
      'Office of the President',
      'Office of the Provost & VP, Academic',
      'Office of Rights and Responsibilities',
      'Office of Sustainability',
      'Office of the VP, Research & Graduate Studies',
      'Office of the VP, Services and Sustainability',
      'University Advancement',
    ],
    departments: [
      'School of Performance (Contemporary Dance, Theatre, Music)',
      'Contemporary Dance',
      'Music',
      'Theatre',
    ],
    amenities: [
      'Accessible',
      'Bike parking',
      'Info desk',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/gm/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750703493618.jpg',
  }),
  row('sgw', 'GN', 'Grey Nuns Building', '1190 Guy St. / 1175 St-Mathieu St.', {
    aliases: [
      'GN',
      'Grey Nuns',
      'Grey Nuns Building',
      'Grey Nuns Mother House',
    ],
    overview: 'Former Grey Nuns Mother House (1871), acquired in 2007. Residence for about 600 undergraduates, with a reading room, observation nursery, and kitchen serving both campuses.',
    accessibility: [
      'Accessibility ramp',
      'Accessible entrance with an automated door',
      'Accessible elevator',
    ],
    venues: [
      'Classroom entrance (1175 St-Mathieu St.)',
      'Grey Nuns Garden',
    ],
    library: 'greynuns',
    services: [
      'Concordia Daycare (1185 St-Mathieu St.)',
      'Concordia University Student Parents Centre (CUSP): 1175 St-Mathieu St.',
      'Grey Nuns Reading Room & Group Study Rooms (1190 Guy St.)',
      'Residences',
      'Summer accommodations',
      'Class Entrance: 1175 St-Mathieu St.',
      'CUSP: 1175 St-Mathieu St. (temporary)',
      'Daycare Centre: 1185 St-Mathieu St.',
      'Grey Nuns Library (reading Room and Group Study Rooms)',
      'Summer Accomodation',
    ],
    departments: [
      'Philosophy (1175 St-Mathieu St.)',
      'Dept. of Philosophy: 1175 St-Mathieu St. (temporary)',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/gn/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750703536218.jpg',
  }),
  row('sgw', 'H', 'Henry F. Hall Building', '1455 De Maisonneuve Blvd. W.', {
    aliases: [
      'H',
      'Hall',
      'Henry F. Hall',
      'Hall Building',
      'Henry F. Hall Building',
    ],
    overview: 'Completed in 1966, the Hall Building is a Brutalist academic and social hub. Social-science departments, classrooms, engineering labs, the Student Success Centre, Concordia Theatre, Hive Café, Reggie\'s, and the People\'s Potato.',
    accessibility: [
      'Accessible entrance with an automated door',
      'Accessible elevator',
    ],
    venues: [
      'Concordia Theatre',
      'Reggie\'s',
      'Sir George Williams University Alumni Auditorium',
    ],
    services: [
      'Campus Safety and Prevention Services',
      'Concordia Student Union (CSU)',
      'First Stop',
      'Espace Franco',
      'IT Service Desk',
      'NouLa Black Student Centre',
      'Office of Student Life and Engagement',
      'Otsenhákta Student Centre',
      'Sexual Assault Resource Centre (SARC)',
      'Student Success Centre',
      'Welcome Crew Office',
      'Zen Den',
    ],
    departments: [
      'Economics',
      'Geography, Planning and Environment',
      'Political Science',
      'Religions and Cultures',
      'School of Community and Public Affairs',
      'School of Irish Studies',
      'Sociology and Anthropology',
    ],
    amenities: [
      'Accessible',
      'ATM',
      'Bike parking',
      'Info desk',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/h/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750703745830.jpg',
  }),
  row('sgw', 'K', 'K Annex', '2150 Bishop St.', {
    aliases: [
      'K Annex',
      'K',
    ],
    overview: 'The oldest of the Bishop annexes, this row house was built in 1890. Its Romanesque-inspired stonework and carved details — like rounded archways and a stone porch with balcony — make it especially striking. Acquired in 1970, the annex now houses offices for departments and unions.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    services: [
      'Concordia Coop Bookstore',
      'CUPFA',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/k/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750704193887.jpg',
  }),
  row('sgw', 'LB', 'J.W. McConnell Building', '1400 De Maisonneuve Blvd. W.', {
    aliases: [
      'LB',
      'McConnell',
      'J.W. McConnell',
      'J.W. McConnell Building',
      'Webster',
      'Webster Library',
    ],
    overview: 'Opened in 1992. Lower floors hold student services, bookstore, print shop and gallery; floors 2–5 are the R. Howard Webster Library. Linked by tunnel to Hall and Guy-Concordia metro.',
    accessibility: [
      'Accessible entrance with an automated door',
      'Accessible elevator',
    ],
    venues: [
      '4TH SPACE',
      'Atrium',
      'J.A. De Sève Cinema',
      'Leonard and Bina Ellen Art Gallery',
      'SHIFT Centre for Social Transformation',
    ],
    library: 'webster',
    services: [
      'Birks Student Service Centre',
      'Concordia Book Stop',
      'Concordia Print Services',
      'First Stop',
      'Instructional and Information Technology Services (IITS)',
      'J.A. De Sève Cinema',
      'R. Howard Webster Library',
      'SHIFT Centre for Social Transformation',
      'Welcome Centre',
      '4TH SPACE',
      'Leonard and Bina Ellen Art Gallery',
      'Office of the Registrar',
      'Sexual Assault Resource Centre (SARC)',
    ],
    departments: [
      'Centre for Interdisciplinary Studies in Society and Culture (CISSC)',
      'Centre for the Study of Learning and Performance',
      'Education',
      'English',
      'Études françaises',
      'History',
      'Mathematics and Statistics',
    ],
    amenities: [
      'Accessible',
      'ATM',
      'Bike parking',
      'Info desk',
      'Parking',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/lb/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750706334758.jpg',
  }),
  row('sgw', 'LD', 'LD Building', '1424 Bishop St.', {
    aliases: [
      'LD Building',
      'LD',
    ],
    overview: 'Built in 1894, this red sandstone townhouse features ornate stonework and a three-storey bay window. Over time, it housed offices, restaurants and cafés. In 2019, Concordia converted the building into a daycare and nursery for the Concordia Student Union. While the interior has evolved, many original architectural features remain visible from the street.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    services: ['CSU Daycare & Nursery'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/ld/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750704279111.jpg',
  }),
  row('sgw', 'LS', 'Learning Square', '1535 De Maisonneuve Blvd. W.', {
    aliases: [
      'LS',
      'Learning Square',
    ],
    overview: 'The Learning Square opened in 2019 to provide extra classroom space while the Henry F. Hall Building underwent renovations. This bright, modular two-storey structure was designed for flexibility and future reuse by Montreal-based firm Lapointe Magne et associés. It houses eight state-of-the-art classrooms and includes universal accessibility features like gender-neutral washrooms and step-free entry.',
    accessibility: [
      'The ground floor of this building is wheelchair accessible, including the individual-use washroom.',
      'Accessibility ramp This building entrance is equipped with an',
      'accessibility ramp.',
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
    ],
    services: [
      'IT Services — 1st floor',
      'IT Services — 2nd floor',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/ls/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750704406530.jpg',
  }),
  row('sgw', 'MB', 'John Molson Building', '1450 Guy St.', {
    aliases: [
      'MB',
      'John Molson',
      'John Molson Building',
      'JMSB',
      'Molson',
    ],
    overview: 'Opened in 2009 at Guy and De Maisonneuve. 15 storeys with teaching amphitheatres, case rooms, research labs, and a tunnel under Guy Street to the metro and EV. LEED Silver.',
    accessibility: [
      'Accessible entrance with an automated door',
      'Accessible elevator',
    ],
    venues: [
      'Concordia Conference Centre, 9th Floor',
      'Cloud Deck',
      'Goodman Institute',
    ],
    services: [
      'Career Management Services',
      'First Stop',
      'John Molson Executive Centre',
      'Performing Arts Facilities',
      'Zen Den',
    ],
    departments: [
      'Accountancy',
      'Executive MBA Program',
      'Finance',
      'Goodman Institute of Investment Management',
      'Management',
      'Marketing',
      'School of Performance (Contemporary Dance, Theatre, Music)',
      'Supply Chain and Business Technology Management',
      'Contemporary Dance',
      'Music',
      'Theatre',
    ],
    amenities: ['Accessible'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/mb/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1752848969887.jpg',
  }),
  row('sgw', 'MI', 'MI Annex', '2130 Bishop St.', {
    aliases: [
      'MI Annex',
      'MI',
    ],
    overview: 'Built in 1891, this red sandstone house was designed in the Richardsonian Romanesque style with bay windows, ironwork and a bold gabled roof. Concordia acquired it in 1971. Once a private home, today the MI Annex hosts union offices.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    services: [
      'Association of Concordia University Management and Administrative Employees (ACUMAE)',
      'Concordia University Continuing Education Part-time Faculty Union (CUCEPTFU)',
      'Concordia University Professional Employee Union (CUPEU)',
      'Concordia University Support Staff Union (CSN)',
      'The Concordia University Union of Support Staff – Technical Sector (CUUSS-TS)',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/mi/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750706431105.jpg',
  }),
  row('sgw', 'MU', 'MU Annex', '2170 Bishop St.', {
    aliases: [
      'MU Annex',
      'MU',
    ],
    overview: 'Built in 1891, the MU Annex blends limestone and textured concrete, giving it a distinct look among the Bishop Street row houses. Once a private home, it was later converted into apartments before being acquired by Concordia in 1971. Today, it provides office space for various university services.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/mu/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750706503707.jpg',
  }),
  row('sgw', 'P', 'P Annex', '2020 Mackay St.', {
    aliases: [
      'P Annex',
      'P',
    ],
    overview: 'Designed and likely built by architect William Tutin Thomas in 1873-74, this three-storey Victorian building includes a striking bay window with a copper-clad oriel. Originally a private residence for brokers and businessmen, the P Annex was acquired by the university in 1969 and is now used for offices and student services.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/p/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750706979083.jpg',
  }),
  row('sgw', 'PR', 'PR Annex', '2100 Mackay St.', {
    aliases: [
      'PR Annex',
      'PR',
    ],
    overview: 'Built around 1957, the PR Annex reflects a modern style with artificial stone at street level and brick above. Its metal accents and clean lines are typical of mid-century design. The four-storey building was acquired by the university in 1974 and now serves as space for offices and student services.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    services: ['Concordia University Library Employees\' Union (CULEU)'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/pr/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750707056205.jpg',
  }),
  row('sgw', 'Q', 'Q Annex', '2010 Mackay St.', {
    aliases: [
      'Q Annex',
      'Q',
    ],
    overview: 'Built in 1875 by architect Alexander Goodsir Fowler, the Q Annex is a modest two-storey Victorian stone home with simple lines and minimal ornamentation. Once home to the Polish Consulate, it became university property in 1969 and now houses offices and student services.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/q/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750707299714.jpg',
  }),
  row('sgw', 'R', 'R Annex', '2050 Mackay St.', {
    aliases: [
      'R Annex',
      'R',
    ],
    overview: 'Built in 1875, the R Annex is one of a trio of similar Victorian houses on this block. It features a stone facade, bay window and intricate slate-roofed dormers. The annex was acquired by the university in 1970 and now houses offices.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    departments: ['Religions and Cultures'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/r/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750712426828.jpg',
  }),
  row('sgw', 'RR', 'RR Annex', '2040 Mackay St.', {
    aliases: [
      'RR Annex',
      'RR',
    ],
    overview: 'The RR Annex, built in 1875, was transformed over the years from a private home to apartments, and even a restaurant in the 1960s. It retains its Victorian charm with a stone bay window mansard roof, and preserved stained glass elements. The building was acquired by Concordia in 1979 and now houses the Liberal Arts College .',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    departments: ['Liberal Arts College'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/rr/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750773247509.jpg',
  }),
  row('sgw', 'T', 'T Annex', '2030 Mackay St.', {
    aliases: [
      'T Annex',
      'T',
    ],
    overview: 'The T Annex dates to 1875 and features a classic Victorian facade of grey stone, with a bay window topped by a copper oriel. The three-storey rowhouse was divided into apartments in 1957 and became university property soon after. The annex now accommodates offices and student services.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    services: ['Graduate Students Association'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/t/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750775449149.jpg',
  }),
  row('sgw', 'V', 'V Annex', '2110 Mackay St.', {
    aliases: [
      'V Annex',
      'V',
    ],
    overview: 'Built in 1937, the V Annex was originally an apartment building called the “Florentia apartments.” This four-storey structure features a white-painted limestone ground floor that contrasts with brown brick above. It was acquired by the university in 1970 and today houses offices and student services. Inside, some original finishes may remain, including a curved staircase and cast-iron radiators.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    services: [
      'Centre for Gender Advocacy',
      'CUTV',
      'Centre 2110',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/v/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750775826854.jpg',
  }),
  row('sgw', 'VA', 'Visual Arts Building', '1395 René-Lévesque Blvd. W.', {
    aliases: [
      'VA',
      'Visual Arts',
      'Visual Arts Building',
    ],
    overview: 'Concordia\'s Visual Arts Building has been home to the Faculty of Fine Arts \' visual arts programs since 1979. Originally built in 1923, the four-storey, L-shaped building features large windows, a concrete structure and a chamomile-coloured façade. Its courtyard entrance and green space out front — once a used car lot — are frequently used for student art installations. Today, the Visual Arts Building houses facilities for the creative arts, including the VAV Gallery , which showcases student artwork to the university community and public.',
    accessibility: [
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
      'Accessible building elevator This building entrance is equipped with an accessible elevator.',
    ],
    accessHours: [
      'Weekdays 7 a.m. to 5 p.m.',
      'No access card required.',
      'Weekdays after 5 p.m. and all day on weekends.',
      'An access-enabled card is required.',
      'Everyday after 11 p.m.',
      'Undergraduate students require: An access-enabled card, and',
      'Special permission from the Department of Studio Arts.',
      'Faculty, staff and graduate students require: An access-enabled card.',
    ],
    services: [
      'VAV Gallery',
      'VAV Art Gallery',
    ],
    departments: [
      'Art Education',
      'Art History',
      'Studio Arts',
      'Creative Arts Therapies',
    ],
    amenities: [
      'Accessible',
      'Bike parking',
      'Info desk',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/va/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750775886127.jpg',
  }),
  row('sgw', 'X', 'X Annex', '2080 Mackay St.', {
    aliases: [
      'X Annex',
      'X',
    ],
    overview: 'Built around 1878, the X Annex is a Victorian home known for its ornate stone details with carved accents around windows and doors. The building was acquired by the university in 1969 and now offers space for offices and student services.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    services: ['Concordia International'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/x/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750776118230.jpg',
  }),

  row('loy', 'AD', 'Administration Building', '7141 Sherbrooke St. W.', {
    aliases: [
      'Administration Building',
      'AD',
    ],
    overview: 'Opened in 1916 and completed in stages through 1927, the Administration Building is one of the original Loyola Campus structures. Designed by architects Peden and McLaren, it features matte Greendale brick with limestone trim, carved wooden details and distinctive oak doors inspired by the University Church of St. Mary the Virgin in Oxford, England. The building is also a Montreal heritage site. Over the years, it has served many purposes — including housing Jesuit priests and student residences — and today it\'s home to Student Services and Faculty of Arts and Science administrative offices. It connects directly to the F.C. Smith (FC) and Central (CC) buildings.',
    accessibility: [
      'Accessibility ramp This building entrance is equipped with an',
      'accessibility ramp.',
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
      'Accessible building elevator This building entrance is equipped with an accessible elevator.',
    ],
    services: [
      'Access Centre for Students with Disabilities',
      'Centre for Teaching and Learning',
      'Counselling and Psychological Services',
      'Loyola College for Diversity and Sustainability',
      'Loyola Landing',
      'Office of the Provost and Vice-President, Academic',
      'Office of Student Life and Engagement',
      'Welcome Crew Office',
      'Dean of Students',
      'Health Services',
      'Loyola International College',
      'Provost and VP, Academic',
    ],
    departments: ['Faculty of Arts and Science'],
    amenities: [
      'Accessible',
      'Bike parking',
      'Info desk',
      'Parking',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/ad/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750701647513.jpg',
  }),
  row('loy', 'BB', 'BB Annex', '3502 Belmore Ave.', {
    aliases: [
      'BB Annex',
      'BB',
    ],
    overview: 'Located on the Loyola Campus, the BB Annex supports campus services that enhance university life. The building is home to CPE les P\'tits Profs , a childcare centre providing high-quality early childhood education to faculty, staff and student families within the Concordia community.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    services: ['CPE Les P\'tits Profs Daycare'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/bb/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1754505281032.jpg',
  }),
  row('loy', 'BH', 'BH Annex', '3500 Belmore Ave.', {
    aliases: [
      'BH Annex',
      'BH',
    ],
    overview: 'The BH Annex is situated on the Loyola Campus. It houses Les P\'tits Profs Daycare , which offers quality childcare for Concordia faculty, staff and students. The building plays a key role in fostering a supportive, family-friendly campus environment.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    services: ['CPE Les P\'tits Profs Daycare'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/bh/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1754505255461.jpg',
  }),
  row('loy', 'CC', 'Central Building', '7141 Sherbrooke St. W.', {
    aliases: [
      'CC',
      'Central',
      'Central Building',
    ],
    overview: 'Opened in 1947, the Central Building was designed in harmony with Loyola Campus\'s original 1913 style. The building connects key spaces at the heart of campus, linking the Administration (AD) Building with the Loyola Jesuit Hall and Conference Centre (RF) and the Psychology (PY) Building . The Central Building originally housed classrooms, a library occupying most of the top floor, a gymnasium, and student bedrooms. Today, it includes classrooms, the Guadagni Lounge — named for beloved professor Franco Guadagni — and the student-run campus radio station, CJLO . Historic Loyola College graduation photos line the second-floor hallway, offering a glimpse into the university\'s past. The building is designated a heritage property by the City of Montreal.',
    accessibility: [
      'Wheelchair lift This building is equipped with a',
      'wheelchair lift.',
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
      'Accessible building elevator This building entrance is equipped with an accessible elevator.',
    ],
    services: [
      'Concordia Student Union',
      'Loyola College for Diversity and Sustainability and Loyola',
      'Zen Den',
    ],
    amenities: [
      'Accessible',
      'Bixi',
      'Info desk',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/cc/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750701910958.jpg',
  }),
  row('loy', 'CJ', 'Communication Studies and Journalism Building', '7141 Sherbrooke St. W.', {
    aliases: [
      'Communication Studies and Journalism Building',
      'CJ',
    ],
    overview: 'Originally built in 1962 as the Drummond Science Complex, this building was fully renovated and expanded in 2005. It now houses the Communication Studies and Journalism departments, as well as a bookstore , open lounge space and small café. The Communication Studies and Journalism Building features specialized media spaces. These include a fully digitized radio and television broadcast operation, network access, high-tech classrooms, new media and computer labs, and studios with high-end audiovisual equipment, including production, video and editing suites.',
    accessibility: [
      'Wheelchair lift This building is equipped with a',
      'wheelchair lift.',
      'Accessibility ramp This building entrance is equipped with an',
      'accessibility ramp.',
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
      'Accessible building elevator This building entrance is equipped with an accessible elevator.',
    ],
    services: [
      'Book Stop',
      'Campus Retail Stores',
    ],
    departments: [
      'Communication Studies',
      'Journalism',
    ],
    amenities: ['Accessible'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/cj/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750702027234.jpg',
  }),
  row('loy', 'DO', 'Stinger Dome', '7141 Sherbrooke St. W.', {
    aliases: [
      'DO',
      'Stinger Dome',
    ],
    services: ['Concordia Stingers'],
    departments: ['Stingers.ca'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/do/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750702189668.jpg',
  }),
  row('loy', 'FC', 'F.C. Smith Building', '7141 Sherbrooke St. W.', {
    aliases: [
      'FC',
      'F.C. Smith Building',
      'F. C. Smith Building',
    ],
    overview: 'The F.C. Smith Building is a multi-use space at Loyola Campus, best known today as home to the Loyola Chapel . Opened in 1933, the building has received a heritage designation from the City of Montreal. The Loyola Chapel offers a beautiful and quiet non-denominational environment, open to people of all faiths for reflection, celebration and community events. The building also hosts classes, events and other activities connected to student life and the broader university community.',
    accessibility: [
      'Accessibility ramp This building entrance is equipped with an',
      'accessibility ramp.',
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
    ],
    venues: ['Loyola Chapel'],
    services: [
      'Cazalet Theatre',
      'Concordia Multi-faith and Spirituality Centre',
      'F.C. Smith Auditorium',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/fc/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750703132721.jpg',
  }),
  row('loy', 'GE', 'Centre for Structural and Functional Genomics', '7141 Sherbrooke St. W.', {
    aliases: [
      'Centre for Structural and Functional Genomics',
      'GE',
    ],
    overview: 'The Centre for Structural and Functional Genomics was officially inaugurated in November 2011 as part of the celebrations marking the 6th year of Montreal\'s designation as a UNESCO City of Design. Located at the corner of Sherbrooke Street West and West Broadway, the centre is among newer structures revitalizing the Loyola Campus, and invigorating the urban landscape in the surrounding Notre-Dame-de-Grâce neighbourhood. The Centre for Structural and Functional Genomics has four floors – 5,400 square metres – dedicated to research facilities . The building is connected to the adjacent Richard J. Renaud Science Complex (SP) through passageways on the second and third floors, as well as a tunnel on the basement level. A tunnel also links the centre with the Communication Studies/Journalism (CJ) Building . This underground network saves students and faculty time and trouble, especially during winter months.',
    accessibility: [
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
      'Accessible building elevator This building entrance is equipped with an accessible elevator.',
    ],
    services: ['Centre for Structural and Functional Genomics'],
    amenities: ['Accessible'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/ge/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1752776070279.jpg',
  }),
  row('loy', 'HA', 'Hingston Hall, wing HA', '7141 Sherbrooke St. W.', {
    aliases: [
      'Hingston Hall, wing HA',
      'HA',
    ],
    overview: 'Opened in 1964, Hingston Hall, wing HA, is one of two wings originally built as a student residence on the Loyola Campus. Today, it still serves this purpose, housing 131 students across its four floors. The building is named after William Hales Hingston, S.J., a key figure in Loyola\'s early development, and honours Loyola\'s tradition of residential student life.',
    accessibility: [
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
    ],
    services: ['Student Residence'],
    amenities: [
      'Accessible',
      'Parking',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/ha/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750703805691.jpg',
  }),
  row('loy', 'HB', 'Hingston Hall, wing HB', '7141 Sherbrooke St. W.', {
    aliases: [
      'Hingston Hall, wing HB',
      'HB',
    ],
    overview: 'Hingston Hall, wing HB, opened in 1964 as part of the original Hingston Hall complex. It underwent major renovations in 2012 to convert the building into a modern student residence. Today, the building provides housing for 118 students, supporting Loyola Campus\' vibrant community.',
    accessibility: [
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
    ],
    services: [
      'Concordia University Faculty Association (CUFA)',
      'Student Residence',
      'CUFA',
    ],
    amenities: [
      'Accessible',
      'Parking',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/hb/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750703951339.jpg',
  }),
  row('loy', 'HC', 'Hingston Hall, wing HC', '7141 Sherbrooke St. W.', {
    aliases: [
      'Hingston Hall, wing HC',
      'HC',
    ],
    overview: 'Hingston Hall, wing HC, the smallest wing of the Hingston complex, complements the residential wings with academic space. It contains offices, classrooms and two amphitheatres, serving as a key space for learning and research at the Loyola Campus.',
    accessibility: [
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
    ],
    services: ['Student Residence'],
    amenities: ['Parking'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/hc/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750703989751.jpg',
  }),
  row('loy', 'HU', 'Applied Science Hub', '7141 Sherbrooke St. W.', {
    aliases: [
      'Applied Science Hub',
      'HU',
    ],
    overview: 'The Applied Science Hub is a state-of-the-art facility on Loyola Campus that opened in December 2020. The hub expands on the Richard J. Renaud Science Complex and reflects Concordia\'s commitment to interdisciplinary research and sustainable design. This LEED Gold–certified building includes four floors of high-tech labs and collaborative spaces, supporting research in agriculture, health, sustainability and engineering. Facilities include equipment for aquatic biology, cellular imaging, nanoscience, bioprocessing and more. The Applied Science Hub also houses the District 3 Innovation Hub , where students, researchers and entrepreneurs can collaborate on scaling up ideas and startups with real-world impact.',
    accessibility: [
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
      'Accessible building elevator This building entrance is equipped with an accessible elevator.',
    ],
    amenities: ['Accessible'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/hu/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1752777007725.jpg',
  }),
  row('loy', 'JR', 'Jesuit Residence', '7141 Sherbrooke St. W.', {
    aliases: [
      'Jesuit Residence',
      'JR',
    ],
    overview: 'Tucked into the northwest corner of Loyola Campus, the Jesuit Residence is a quiet, seven-storey building with a long history. Originally built in 1969 to house the Jesuit priests of Loyola College, it remained in use by the Jesuit Order until Concordia purchased the property. The residence reopened for student housing in 2006. Today, the residence offers 52 private rooms spread across six floors. The top floor offers common areas for cooking, eating and small gatherings, while the basement has a laundry room and a games room.',
    accessibility: [
      'Accessibility ramp This building entrance is equipped with an',
      'accessibility ramp.',
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
      'Accessible building elevator This building entrance is equipped with an accessible elevator.',
    ],
    services: ['Student Residence'],
    amenities: ['Parking'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/jr/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1752775378408.jpg',
  }),
  row('loy', 'PC', 'PERFORM Centre', '7200 Sherbrooke St. W.', {
    aliases: [
      'PERFORM Centre',
      'PC',
    ],
    overview: 'Located on the south side of Sherbrooke Street at the Loyola Campus, the PERFORM Centre building, which houses the School of Health and its laboratories , makes a striking impression as it inclines towards de Maisonneuve Street. Students and the general public can join fitness classes, work out or consult with a personal trainer at the PERFORM Gym , as well as meet with a dietitian , attend workshops or visit kinesiology and athletic therapy internship clinics. Designed with natural lighting and advanced energy recuperation systems, the centre earned LEED Gold certification in 2011 for its sustainable construction.',
    accessibility: [
      'Accessibility ramp This building entrance is equipped with an',
      'accessibility ramp.',
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
      'Accessible building elevator This building entrance is equipped with an accessible elevator.',
    ],
    services: [
      'Athletic Therapy Clinic',
      'Health Services',
      'Nutrition Centre',
      'PERFORM Gym',
      'School of Health',
    ],
    amenities: [
      'Accessible',
      'Info desk',
      'Parking',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/pc/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1754056606860.jpg',
  }),
  row('loy', 'PS', 'Physical Services Building', '7141 Sherbrooke St. W.', {
    aliases: [
      'Physical Services Building',
      'PS',
    ],
    overview: 'Built in 1923 as the Loyola College Arena, the Physical Services Building has played many roles over the years. Originally home to the college\'s first rink, it was expanded in 1941 with a south wall addition to house a Canadian Officers Training Corps (COTC) drill hall, which was later repurposed as a cafeteria after World War II. Following the opening of the Athletics Complex in 1967 and the relocation of the COTC, the building was converted for Facilities Operations Services. Today, this two-storey structure continues to support Concordia\'s Facilities Operations Services and also serves as a workspace for student theatre workshops and engineering projects, including vehicle design and fabrication initiatives.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    services: [
      'Environmental Health and Safety',
      'Facilities Management',
    ],
    amenities: ['Accessible'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/ps/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1753211858581.jpg',
  }),
  row('loy', 'PT', 'Oscar Peterson Concert Hall', '7141 Sherbrooke St. W.', {
    aliases: [
      'Oscar Peterson Concert Hall',
      'PT',
    ],
    overview: 'Opened in 1990, the Oscar Peterson Concert Hall is a 513-seat venue used for concerts, lectures, recordings and other performances. The concert hall features adjustable acoustics and a birch-paneled stage backdrop. Originally called the Concordia Concert Hall, it was renamed in 1999 for Montreal jazz legend Oscar Peterson, a former Loyola Medalist and honorary degree recipient. The concert hall is connected to the Student Centre and Vanier Library .',
    accessibility: [
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
    ],
    services: ['Concert Hall'],
    departments: ['Oscar Peterson Concert Hall'],
    amenities: ['Accessible'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/pt/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750712426795.jpg',
  }),
  row('loy', 'PY', 'Psychology Building', '7141 Sherbrooke St. W.', {
    aliases: [
      'Psychology Building',
      'PY',
    ],
    overview: 'The Psychology Building, one of Loyola Campus\'s original buildings, was first known as the Junior Building and served both high school and college students. Built around 1927, it was expanded in 1969 with a modern addition and fully renovated in the early 1990s to house the Department of Psychology . The three-storey L-shaped structure, with its historic detailing and large classrooms, once included a chapel and dormitories. Today, it features offices, labs and classrooms and remains directly connected to the Loyola Jesuit Hall and Conference Centre (RF) .',
    accessibility: [
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
      'Accessible building elevator This building entrance is equipped with an accessible elevator.',
    ],
    departments: [
      'Centre for Clinical Research in Health (CCRH)',
      'Psychology',
    ],
    amenities: ['Info desk'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/py/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750712426337.jpg',
  }),
  row('loy', 'QA', 'Quadrangle', '7141 Sherbrooke St. W.', {
    aliases: [
      'Quadrangle',
      'QA',
    ],
    amenities: ['Accessible'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/qa/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750712426399.jpg',
  }),
  row('loy', 'RA', 'Recreation and Athletics Complex', '7200 Sherbrooke St. W.', {
    aliases: [
      'Recreation and Athletics Complex',
      'RA',
    ],
    overview: 'Opened in 1967, the Recreation and Athletics Complex is the heart of varsity and recreational sports at Concordia\'s Loyola Campus. It features the NHL-standard Ed Meagher Arena , a 4,000-seat stadium, gymnasium and two outdoor turf fields. Today, the complex is home to Concordia Stingers varsity teams, intramural leagues , fitness classes and community sports programs. Students can join pick-up games or participate in organized leagues for basketball, volleyball, soccer, rugby and more.',
    accessibility: [
      'Wheelchair lift This building is equipped with a',
      'wheelchair lift.',
      'Accessibility ramp This building entrance is equipped with an',
      'accessibility ramp.',
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
    ],
    venues: [
      'Concordia Stadium',
      'Ed Meagher Arena',
      'Gymnasium',
    ],
    services: [
      'Ed Meagher Arena',
      'Gymnasium',
    ],
    amenities: [
      'Accessible',
      'Parking',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/ra/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1753387180607.jpg',
  }),
  row('loy', 'RF', 'Loyola Jesuit Hall and Conference Centre', '7141 Sherbrooke St. W.', {
    aliases: [
      'Loyola Jesuit Hall and Conference Centre',
      'RF',
    ],
    overview: 'Originally known as the Refectory, this historic building is one of the oldest structures on the Loyola Campus. Built in the shape of a cross, it originally featured elegant dining halls, an infirmary and a distinctive sundial on its south façade. In 2012, the building officially reopened as the Loyola Jesuit Hall and Conference Centre after a major restoration. This transformation marked a key milestone in the revitalization of the Loyola Campus. Today, this historic building is an important gathering place for community and social events . The space includes an alumni centre, lounge, large conference and meeting rooms, catering facilities and offices.',
    accessibility: [
      'Wheelchair lift This building is equipped with a',
      'wheelchair lift.',
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
    ],
    services: [
      'Conference services',
      'Loyola Jesuit Hall and Conference Centre',
    ],
    amenities: ['Accessible'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/rf/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1754321077294.jpg',
  }),
  row('loy', 'SC', 'Student Centre', '7141 Sherbrooke St. W.', {
    aliases: [
      'Student Centre',
      'SC',
    ],
    overview: 'Opened in 1973, the Student Centre was designed as a space for students, by students. It originally housed lounges, music-listening spaces and a student pub, The Wolf and Kettle — later renamed The Hive. Today, the building hosts Buzz Dining Hall , the Hive Café , music practice rooms and student association offices. Built with student and alumni contributions, the centre was refreshed through the “Revive the Hive” campaign in the late 1990s. It connects directly to the Oscar Peterson Concert Hall and Vanier Library .',
    accessibility: [
      'Accessibility ramp This building entrance is equipped with an',
      'accessibility ramp.',
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
    ],
    services: [
      'Cafeteria',
      'Café',
      'Food Services',
    ],
    amenities: ['Accessible'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/sc/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750774420596.jpg',
  }),
  row('loy', 'SH', 'Future Buildings Laboratory', '7141 Sherbrooke St. W.', {
    aliases: [
      'SH',
      'Future Buildings Laboratory',
      'Solar House',
    ],
    overview: 'Completed in 2021, the Future Buildings Laboratory supports research and innovation in sustainable buildings and infrastructure. It carries forward the legacy of Concordia\'s Solar House, originally designed for the university\'s entry in the prestigious U.S. Solar Decathlon in 2005. After the competition, the house was reassembled on campus as a permanent research facility. Today, the laboratory serves as a world-class living lab where students and researchers explore net-zero energy envelope design, intelligent building systems and renewable nano-grid integration.',
    accessibility: [
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/sh/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750774494391.jpg',
  }),
  row('loy', 'SP', 'Richard J. Renaud Science Complex', '7141 Sherbrooke St. W.', {
    aliases: [
      'SP',
      'Science Complex',
      'Richard J. Renaud Science Complex',
      'Renaud',
    ],
    overview: 'Opened in 2003, the Richard J. Renaud Science Complex changed the face of Concordia\'s west-end campus. This state-of-the-art teaching and research facility includes teaching facilities, offices and laboratories for various science departments. The avant-garde design promotes interdisciplinarity and innovation in one of the top university sciences facilities in Canada. The award-winning building also features energy-efficient sustainable architecture. The complex includes the former Bryan Building (built in 1968), which has been completely renovated and fully integrated into the new structure. The complex connects directly to the Centre for Structural and Functional Genomics (GE) , Applied Science Hub (HU) and the Loyola Jesuit Hall and Conference Centre (RF) .',
    accessibility: [
      'Accessibility ramp This building entrance is equipped with an',
      'accessibility ramp.',
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
      'Accessible building elevator This building entrance is equipped with an accessible elevator.',
    ],
    services: [
      'Café',
      'Campus Safety and Prevention Services',
      'First Stop',
      'Science College',
      'Science Technical Centre',
    ],
    departments: [
      'Biology',
      'Centre for Biological Applications of Mass Spectrometry',
      'Centre for NanoScience Research',
      'Centre for Research in Molecular Modeling',
      'Centre for Studies in Behavioral Neurobiology',
      'Chemistry and Biochemistry',
      'Health, Kinesiology and Applied Physiology',
      'Physics',
      'Psychology',
    ],
    amenities: [
      'Accessible',
      'Info desk',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/sp/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1753215175111.jpg',
  }),
  row('loy', 'TA', 'Terrebonne Building', '7079 de Terrebonne St.', {
    aliases: [
      'Terrebonne Building',
      'TA',
    ],
    overview: 'Located a short walk from the heart of Loyola Campus, Concordia\'s Terrebonne Building is a standalone facility that plays an important role in the university\'s campus network. It houses the Centre for the Arts in Human Development (CAHD) — an educational, clinical and research centre serving adults with disabilities, neurodivergence and other needs.',
    accessibility: [
      'This building is not accessible. It is not equipped with an',
      'accessibility ramp, automated door, elevator or',
      'wheelchair lift.',
    ],
    departments: ['Centre for the Arts in Human Development (CAHD)'],
    amenities: ['Parking'],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/ta/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1759152574654.jpg',
  }),
  row('loy', 'VE', 'Vanier Extension', '7141 Sherbrooke St. W.', {
    aliases: [
      'VE',
      'Vanier Extension',
    ],
    overview: 'Originally built in 1964 as Loyola\'s first library, this structure became known as the Vanier Extension after the new Vanier Library opened in 1989. Today, the Extension offers flexible, digitally equipped classrooms and also houses spaces for the Department of Applied Human Sciences . The building is directly connected to the Vanier Library and other campus buildings, and features public art, including The Four Horsemen by François Houde, installed in 1989.',
    accessibility: [
      'Accessible entrance This building has an automated',
      'accessible entrance door.',
      'Accessible building elevator This building entrance is equipped with an accessible elevator.',
    ],
    library: 'vanier',
    services: ['Library'],
    departments: ['Applied Human Sciences'],
    amenities: [
      'Accessible',
      'Bike parking',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/ve/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1754323922442.jpg',
  }),
  row('loy', 'VL', 'Vanier Library Building', '7141 Sherbrooke St. W.', {
    aliases: [
      'VL',
      'Vanier',
      'Vanier Library',
      'Georges P. Vanier Library',
      'Vanier Library Building',
    ],
    overview: 'Named for Loyola alumnus Georges P. Vanier. Library since 1964; doubled in 1989 with the Vanier Extension. Silent and collaborative study, 22 learning spaces, and bookable group rooms.',
    accessibility: [
      'Accessible entrance with an automated door',
      'Accessible elevator',
    ],
    library: 'vanier',
    services: [
      'Georges P. Vanier Library',
      'Library',
    ],
    amenities: [
      'Accessible',
      'Info desk',
    ],
    imageUrl: 'https://www.concordia.ca/content/concordia/en/maps/buildings/vl/_jcr_content/content-main/grid_container_307846512/grid-container-parsys/box_427340212/box-parsys/image.img.jpg/1750775944461.jpg',
  }),
];

const catalogByKey = new Map(
  BUILDING_CATALOG.map((record) => [`${record.campusId}-${record.code.toUpperCase()}`, record])
);

export function getBuildingCatalogRecord(
  campusId: CampusCode,
  code: string
): BuildingCatalogRecord | undefined {
  return catalogByKey.get(`${campusId}-${code.trim().toUpperCase()}`);
}

/** Flattened services/departments index for campus search. */
export function getCampusServices(campusId: CampusCode): ServiceSearchResult[] {
  const results: ServiceSearchResult[] = [];

  BUILDING_CATALOG.filter((building) => building.campusId === campusId).forEach((building) => {
    (building.services ?? []).forEach((label, index) => {
      results.push({
        id: `svc-${campusId}-${building.code}-${index}-${label}`,
        label,
        buildingName: building.name,
        buildingCode: building.code,
        kind: 'service',
      });
    });
    (building.departments ?? []).forEach((label, index) => {
      results.push({
        id: `dept-${campusId}-${building.code}-${index}-${label}`,
        label,
        buildingName: building.name,
        buildingCode: building.code,
        kind: 'department',
      });
    });
  });

  return results.sort((a, b) =>
    `${a.label} - ${a.buildingName}`.localeCompare(`${b.label} - ${b.buildingName}`)
  );
}
