import type { BuildingSummary } from '@/types/campus';

/**
 * Curated buildings used when Open Data is unavailable.
 * Coordinates are approximate public campus locations.
 */
export const BUILDING_FALLBACK: BuildingSummary[] = [
  {
    id: 'fallback-sgw-gm',
    campusId: 'sgw',
    code: 'GM',
    name: 'Guy-De Maisonneuve',
    longName: 'Guy-De Maisonneuve Building',
    address: '1550 De Maisonneuve Blvd. W.',
    lat: 45.49595,
    lng: -73.57874,
    amenities: [],
  },
  {
    id: 'fallback-sgw-h',
    campusId: 'sgw',
    code: 'H',
    name: 'Henry F. Hall',
    longName: 'Henry F. Hall Building',
    address: '1455 De Maisonneuve Blvd. W.',
    lat: 45.49719,
    lng: -73.57895,
    amenities: [],
  },
  {
    id: 'fallback-sgw-lb',
    campusId: 'sgw',
    code: 'LB',
    name: 'J.W. McConnell',
    longName: 'J.W. McConnell Building',
    address: '1400 De Maisonneuve Blvd. W.',
    lat: 45.49688,
    lng: -73.57805,
    amenities: [],
  },
  {
    id: 'fallback-sgw-mb',
    campusId: 'sgw',
    code: 'MB',
    name: 'John Molson',
    longName: 'John Molson Building',
    address: '1450 Guy St.',
    lat: 45.49525,
    lng: -73.5791,
    amenities: [],
  },
  {
    id: 'fallback-sgw-ev',
    campusId: 'sgw',
    code: 'EV',
    name: 'Engineering, Computer Science and Visual Arts',
    longName: 'Engineering, Computer Science and Visual Arts Integrated Complex',
    address: '1515 Ste-Catherine St. W.',
    lat: 45.49545,
    lng: -73.5778,
    amenities: [],
  },
  {
    id: 'fallback-loy-cc',
    campusId: 'loy',
    code: 'CC',
    name: 'Central',
    longName: 'Central Building',
    address: '7141 Sherbrooke St. W.',
    lat: 45.4582,
    lng: -73.6405,
    amenities: [],
  },
  {
    id: 'fallback-loy-sp',
    campusId: 'loy',
    code: 'SP',
    name: 'Richard J. Renaud Science Complex',
    longName: 'Richard J. Renaud Science Complex',
    address: '7141 Sherbrooke St. W.',
    lat: 45.4574,
    lng: -73.6414,
    amenities: [],
  },
  {
    id: 'fallback-loy-vl',
    campusId: 'loy',
    code: 'VL',
    name: 'Vanier Library',
    longName: 'Vanier Library Building',
    address: '7141 Sherbrooke St. W.',
    lat: 45.4589,
    lng: -73.6389,
    amenities: [],
  },
];
