export { MaterialSymbol } from './MaterialSymbol';
export {
  tabSymbols,
  featureSymbols,
  meAccountSymbols,
  msSchool,
  msAssignment,
  msScheduleClock,
  msPayments,
  msWorkspacePremium,
  msHowToReg,
  msComputer,
  msMenuBook,
  msBarChart,
  msChevronLeft,
  msChevronRight,
  msChevronRightSemibold,
  msWbSunny,
  msPerson,
  msSecurity,
  msSearch,
  msLocationOn,
  msClose,
  msNotifications,
  msSettings,
  msBadge,
  msRestaurant,
  msPrint,
  msLocalParking,
  msLock,
  msBookmark,
  msBookmarkFill,
  msExpandMore,
  msCheck,
  msAdd,
  msCalendarMonth,
  msEvent,
} from './symbols';
export type { TabSymbolPair, FeatureSymbolKey } from './symbols';
